services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL="postgresql://postgres:ilu>c8cs@host.docker.internal:5433/AthletIQ"
      - NODE_ENV=development
      - JWT_SECRET=supersecretjwtkey
    extra_hosts:
      - "host.docker.internal:host-gateway"
